# Jekyll config

# Site settings
title: Co-op Experience Library
description: Guidelines, tools and resources to help us create better digital experiences for our customers.
baseurl: ""
url: "http://pioneer-design-system.heroku.com"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
