# Jekyll config

# Site settings
title: Co-op Design System
description: Co-op Design System
baseurl: ""
url: "http://coop-prototyping-kit.heroku.com"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
