# Jekyll config

# Site settings
title: Co-op Experience Library
description: Guidelines, tools and resources to help us create better digital experiences for our customers.

# Deploying to Heroku
baseurl: ""
url: ""

# Deploying to Co-op infrastructure
# baseurl: "/experience-library"
# url: "https://static.coop.co.uk"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
gems:
  - jekyll-remote-include