# Jekyll config

# Site settings
title: Co-op Experience library
description: Tools and resources to help ensure Co-op creates coherent, efficient customer experiences to the highest standard.
baseurl: ""
url: "http://coop-prototyping-kit.heroku.com"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
